
import { GoogleGenAI, Type } from "@google/genai";
import { GameLevel, WordPair } from "../types";

// Vocabulary data from Units 1-6
const UNIT_WORDS: Record<GameLevel, WordPair[]> = {
  [GameLevel.Unit1]: [
    { en: "name", cn: "名字" },
    { en: "nice", cn: "令人愉快的; 友好的" },
    { en: "ear", cn: "耳朵" },
    { en: "hand", cn: "手" },
    { en: "eye", cn: "眼睛" },
    { en: "mouth", cn: "嘴" },
    { en: "arm", cn: "胳膊" },
    { en: "can", cn: "可以" },
    { en: "share", cn: "分享" },
    { en: "smile", cn: "微笑; 笑" },
    { en: "listen", cn: "听; 倾听" },
    { en: "help", cn: "帮助" },
    { en: "say", cn: "说; 讲" },
    { en: "friend", cn: "朋友" },
    { en: "good", cn: "好的" },
  ],
  [GameLevel.Unit1Supplement]: [
    { en: "I", cn: "我 (主格)" },
    { en: "my", cn: "我的" },
    { en: "we", cn: "我们 (主格)" },
    { en: "our", cn: "我们的" },
    { en: "you", cn: "你, 你们" },
    { en: "your", cn: "你的, 你们的" },
    { en: "me", cn: "我 (宾格)" },
    { en: "us", cn: "我们 (宾格)" },
    { en: "meet", cn: "遇见, 见到" },
    { en: "wave", cn: "挥手, 挥动" },
    { en: "point", cn: "指着, 指出" },
    { en: "thank", cn: "感谢, 谢谢" },
    { en: "play", cn: "玩, 玩耍" },
    { en: "look", cn: "看" },
    { en: "together", cn: "一起" },
    { en: "new", cn: "新的" },
    { en: "let", cn: "让" },
    { en: "what", cn: "什么" },
    { en: "am、is、are", cn: "是" },
  ],
  [GameLevel.Unit2]: [
    { en: "mum", cn: "(口语)妈妈" },
    { en: "dad", cn: "(口语)爸爸; 爹爹" },
    { en: "grandma", cn: "奶奶; 姥姥" },
    { en: "grandpa", cn: "爷爷; 姥爷" },
    { en: "grandfather", cn: "(外)祖父; 爷爷; 姥爷; 外公" },
    { en: "grandmother", cn: "(外)祖母; 奶奶; 姥姥; 外婆" },
    { en: "mother", cn: "母亲; 妈妈" },
    { en: "father", cn: "父亲; 爸爸" },
    { en: "me", cn: "我" },
    { en: "sister", cn: "姐; 妹" },
    { en: "family", cn: "家; 家庭" },
    { en: "have", cn: "有" },
    { en: "big", cn: "大的" },
    { en: "cousin", cn: "堂(表)兄弟; 堂(表)姐妹" },
    { en: "brother", cn: "哥; 弟" },
    { en: "baby", cn: "婴儿" },
    { en: "uncle", cn: "伯父; 叔父; 舅父; 姑父; 姨父" },
    { en: "aunt", cn: "伯母; 婶母; 舅母; 姑母; 姨母" },
    { en: "small", cn: "小的" },
  ],
  [GameLevel.Unit2Supplement]: [
    { en: "this", cn: "这" },
    { en: "that", cn: "那" },
    { en: "tree", cn: "树" },
    { en: "family tree", cn: "族谱" },
    { en: "talk", cn: "交流, 交谈" },
    { en: "love", cn: "爱" },
    { en: "two", cn: "二" },
    { en: "fine", cn: "很好" },
    { en: "a/an", cn: "一个" },
    { en: "he", cn: "他" },
    { en: "she", cn: "她" },
    { en: "they", cn: "他们" }
  ],
  [GameLevel.Unit3]: [
    { en: "like", cn: "喜欢" },
    { en: "dog", cn: "狗" },
    { en: "pet", cn: "宠物" },
    { en: "cat", cn: "猫" },
    { en: "fish", cn: "鱼; 鱼肉" },
    { en: "bird", cn: "鸟" },
    { en: "rabbit", cn: "兔" },
    { en: "go", cn: "去; 走" },
    { en: "zoo", cn: "动物园" },
    { en: "fox", cn: "狐狸" },
    { en: "Miss", cn: "(学生对女教师的称呼)老师; 女士" },
    { en: "panda", cn: "大熊猫" },
    { en: "red panda", cn: "小熊猫" },
    { en: "cute", cn: "可爱的" },
    { en: "monkey", cn: "猴子" },
    { en: "tiger", cn: "老虎" },
    { en: "elephant", cn: "大象" },
    { en: "lion", cn: "狮; 狮子" },
    { en: "animal", cn: "动物" },
    { en: "giraffe", cn: "长颈鹿" },
    { en: "tall", cn: "高的" },
    { en: "fast", cn: "快的" },
  ],
  [GameLevel.Unit3Supplement]: [
    { en: "morning", cn: "早上" },
    { en: "come", cn: "来" },
    { en: "run", cn: "跑" },
    { en: "swim", cn: "游泳" },
    { en: "sleep", cn: "睡" },
    { en: "wild", cn: "野生的" },
    { en: "sing", cn: "唱" },
    { en: "song", cn: "歌" },
  ],
  [GameLevel.Unit4]: [
    { en: "apple", cn: "苹果" },
    { en: "banana", cn: "香蕉" },
    { en: "farm", cn: "农场" },
    { en: "air", cn: "空气" },
    { en: "orange", cn: "橙子; 柑橘" },
    { en: "grape", cn: "葡萄" },
    { en: "school", cn: "学校" },
    { en: "garden", cn: "花园" },
    { en: "need", cn: "需要" },
    { en: "water", cn: "给...浇水; 水" },
    { en: "flower", cn: "花; 花朵" },
    { en: "grass", cn: "草; 草地" },
    { en: "plant", cn: "种植; 植物" },
    { en: "new", cn: "新的" },
    { en: "tree", cn: "树" },
    { en: "sun", cn: "阳光; 太阳" },
    { en: "give", cn: "给" },
    { en: "them", cn: "它们; 他/她们" },
  ],
  [GameLevel.Unit5]: [
    { en: "colour", cn: "颜色" },
    { en: "orange", cn: "橙红色; 橙红色的" },
    { en: "green", cn: "绿色; 绿色的" },
    { en: "red", cn: "红色; 红色的" },
    { en: "blue", cn: "蓝色; 蓝色的" },
    { en: "make", cn: "使出现; 做" },
    { en: "purple", cn: "紫色; 紫色的" },
    { en: "brown", cn: "棕色; 棕色的" },
    { en: "bear", cn: "熊" },
    { en: "yellow", cn: "黄色; 黄色的" },
    { en: "duck", cn: "鸭" },
    { en: "sea", cn: "海; 海洋" },
    { en: "some", cn: "一些" },
    { en: "pink", cn: "粉色; 粉色的" },
    { en: "draw", cn: "画" },
    { en: "white", cn: "白色; 白色的" },
    { en: "black", cn: "黑色; 黑色的" },
  ],
  [GameLevel.Unit6]: [
    { en: "old", cn: "(多少)岁; 年纪; 旧的" },
    { en: "five", cn: "五" },
    { en: "year", cn: "年纪; 年" },
    { en: "one", cn: "一" },
    { en: "two", cn: "二" },
    { en: "three", cn: "三" },
    { en: "four", cn: "四" },
    { en: "ten", cn: "十" },
    { en: "six", cn: "六" },
    { en: "seven", cn: "七" },
    { en: "eight", cn: "八" },
    { en: "nine", cn: "九" },
    { en: "o'clock", cn: "(表示整点)...点钟" },
    { en: "cut", cn: "切块" },
    { en: "eat", cn: "吃" },
    { en: "cake", cn: "蛋糕" },
  ],
  [GameLevel.Custom]: [],
};

// Sentence/Dialogue data
const UNIT_SENTENCES: Record<GameLevel, WordPair[]> = {
  [GameLevel.Unit1]: [
    { en: "Hello, I'm Mike.", cn: "你好，我是麦克。" },
    { en: "Hello, my name is Mike.", cn: "你好，我的名字是麦克。" },
    { en: "Nice to meet you.", cn: "见到你很开心。" },
    { en: "Nice to meet you, too.", cn: "见到你也很开心。" },
    { en: "Wave your hand.", cn: "挥挥你的手。" },
    { en: "Wave your arm.", cn: "挥挥你的手臂。" },
    { en: "Look into my eyes.", cn: "看着我的眼睛" },
    { en: "Point to your mouth. Smile!", cn: "指着你的嘴巴，笑！" },
    { en: "Point to your ears. Listen!", cn: "指着你的耳朵，听！" },
    { en: "Point to your eyes. Look!", cn: "指着你的眼睛，看！" },
    { en: "We can share.", cn: "我们可以分享。" },
    { en: "Thank you, Mike.", cn: "谢谢你，麦克。" },
    { en: "Thanks, Mike.", cn: "谢谢，麦克。" },
    { en: "I am nice to my friends.", cn: "我对我的朋友们很友好。" },
    { en: "Mike is my new friend.", cn: "麦克是我的新朋友。" },
    { en: "We play together.", cn: "我们一起玩。" },
    { en: "We are good friends now.", cn: "我们现在是好朋友。" },
    { en: "Let's be friends.", cn: "让我们做朋友吧。" },
    { en: "What's your name?", cn: "你的名字是什么？" }
  ],
  [GameLevel.Unit2]: [
    { en: "This is my family.", cn: "这是我的家庭。" },
    { en: "That is my grandpa.", cn: "那是我的爷爷。" },
    { en: "This is my friend.", cn: "这是我的朋友。" },
    { en: "That is my father.", cn: "那是我的父亲。" },
    { en: "Is this your sister?", cn: "这是你的姐姐吗？" },
    { en: "Is that your aunt?", cn: "那是你的姑姑吗？" },
    { en: "Yes, it is.", cn: "是的。" },
    { en: "No, it's my cousin.", cn: "不，这是我的表姐。" },
    { en: "Is that your brother?", cn: "那是你的兄弟吗？" },
    { en: "No, it is my cousin.", cn: "不，那是我的堂(表)兄弟/姐妹。" },
    { en: "I have a sister.", cn: "我有一个妹妹。" },
    { en: "I have two brothers.", cn: "我有两个弟弟。" },
    { en: "This family is big.", cn: "这个家庭很大。" },
    { en: "This family is small.", cn: "这个家庭很小。" },
    { en: "I love my family.", cn: "我爱我的家庭。" },
    { en: "How are you?", cn: "你好吗？" },
    { en: "I'm fine, thank you.", cn: "我很好，谢谢你。" },
    { en: "I play with my brothers.", cn: "我和我的兄弟们一起玩耍。" },
    { en: "I share with my sisters.", cn: "我和我的姐妹们一起分享。" },
    { en: "I talk with my cousins.", cn: "我和我的堂兄弟们交谈。" }
  ],
  // Empty defaults for other levels
  [GameLevel.Unit1Supplement]: [],
  [GameLevel.Unit2Supplement]: [],
  [GameLevel.Unit3]: [],
  [GameLevel.Unit3Supplement]: [],
  [GameLevel.Unit4]: [],
  [GameLevel.Unit5]: [],
  [GameLevel.Unit6]: [],
  [GameLevel.Custom]: [],
};

export const fetchWordPairs = async (level: GameLevel): Promise<WordPair[]> => {
  // If it's a preset unit, return data immediately (no AI needed)
  if (level !== GameLevel.Custom && UNIT_WORDS[level] && UNIT_WORDS[level].length > 0) {
    return UNIT_WORDS[level];
  }

  // Fallback for custom or empty levels (though custom decks are handled in App.tsx)
  return [];
};

export const fetchSentences = async (level: GameLevel): Promise<WordPair[]> => {
  if (level !== GameLevel.Custom && UNIT_SENTENCES[level] && UNIT_SENTENCES[level].length > 0) {
    return UNIT_SENTENCES[level];
  }
  return [];
};
